version: "3.8"

services:

  mysql:
    image: mysql:8.4
    container_name: rubrica_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
