version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: ticket-system-php
    ports:
      - "3000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
      a2enmod rewrite &&
      chown -R www-data:www-data /var/www/html &&
      chmod -R 755 /var/www/html &&
      apache2-foreground
      "
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge